# Generated by Django 3.1.7 on 2022-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_register',
            name='user_img',
            field=models.FileField(max_length=2000, upload_to=None),
        ),
    ]
