# Generated by Django 3.1.7 on 2022-09-02 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0003_remove_model_register_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_register',
            name='id',
        ),
        migrations.AddField(
            model_name='model_register',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_register',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone_Number'),
        ),
    ]
