# Generated by Django 3.1.7 on 2022-09-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0004_auto_20220902_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default='6000', verbose_name='Rent')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=100, verbose_name='Month')),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgms_app.model_register')),
            ],
        ),
    ]
