# Generated by Django 3.1.7 on 2022-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0005_model_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_rent',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
