# Generated by Django 3.1.7 on 2022-09-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0009_auto_20220903_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_rent',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone_Number'),
        ),
    ]
