# Generated by Django 3.1.7 on 2022-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0010_auto_20220903_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_rent',
            name='month',
        ),
        migrations.AddField(
            model_name='model_rent',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
