# Generated by Django 3.1.7 on 2022-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0011_auto_20220903_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_rent',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
