# Generated by Django 3.1.7 on 2022-09-03 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pgms_app', '0012_auto_20220903_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_rent',
            name='uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='User_Name'),
            preserve_default=False,
        ),
    ]
